name = "MapMaskZz"
uuid = "ede75e6b-e38f-4655-aabe-54824c7f5bfe"
authors = ["Arnold"]
version = "0.1.0"

[deps]
BaseZz = "76171be9-0d6b-4c15-96ae-d6a41202f9dc"

[compat]
BaseZz = "0.1.0"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
